# Generated by Django 5.0.6 on 2024-07-09 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_user_alter_staypics_customer_delete_myuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staypics',
            name='customer',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
