# Generated by Django 5.0.6 on 2024-07-05 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_staypics_adults_remove_staypics_bedtype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staypics',
            name='customer',
        ),
    ]
