# Generated by Django 5.0.6 on 2024-07-06 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BedField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed', models.CharField(choices=[('King', 'King Room'), ('Twin', 'Twin Room'), ('Grand', 'Grand Executive Suite')], default='King', max_length=6)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='BookData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin', models.DateField()),
                ('checkout', models.DateField()),
                ('adults', models.PositiveIntegerField(default=2)),
                ('children', models.PositiveIntegerField(default=0)),
                ('bedtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookDetails.bedfield')),
            ],
        ),
    ]
