# Generated by Django 5.0.6 on 2024-07-05 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed', models.CharField(choices=[('King', 'King Room'), ('Twin', 'Twin Room'), ('Grand', 'Grand Executive Suite')], default='King', max_length=6)),
                ('price', models.CharField(max_length=10)),
            ],
        ),
    ]
