# Generated by Django 5.0.6 on 2024-07-05 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookDetails', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookingField',
            new_name='BedField',
        ),
    ]
