# Generated by Django 5.0.6 on 2024-07-05 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookDetails', '0002_rename_bookingfield_bedfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin', models.DateField()),
                ('checkout', models.DateField()),
                ('adults', models.PositiveIntegerField(default=2)),
                ('children', models.PositiveIntegerField(default=0)),
                ('bedtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookDetails.bedfield')),
            ],
        ),
    ]
